name: polychrom-hoomd
channels:
    - conda-forge
dependencies:
    - pip
    - python>=3.0
    - numpy>=1.9
    - scipy>=0.16
    - matplotlib>=2.0
    - pandas>=0.19
    - hoomd>=3.0
    - fresnel>=0.13
    - gsd>=2.8
    - pip:
        - cython
        - ipython
        - joblib
        - notebook
        - tornado==6.0.0
        - git+https://github.com/open2c/polykit.git
